version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cs2beta-postgres
    environment:
      POSTGRES_DB: cs2beta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cs2beta-network
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: cs2beta-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cs2beta-network
    restart: unless-stopped

  # Backend API
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: cs2beta-backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/cs2beta
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - cs2beta-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
        VITE_ENABLE_ANALYTICS: ${VITE_ENABLE_ANALYTICS:-false}
        VITE_ENABLE_MOCK_DATA: ${VITE_ENABLE_MOCK_DATA:-false}
        VITE_ENABLE_PWA: ${VITE_ENABLE_PWA:-false}
    container_name: cs2beta-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cs2beta-network
    restart: unless-stopped

  # Drizzle Studio (Database GUI) - Optional for development
  drizzle-studio:
    image: ghcr.io/drizzle-team/drizzle-studio:latest
    container_name: cs2beta-drizzle-studio
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/cs2beta
    ports:
      - "4983:4983"
    depends_on:
      - postgres
    networks:
      - cs2beta-network
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:

networks:
  cs2beta-network:
    driver: bridge 